version: '3.3'
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: 'canoe'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init:/docker-entrypoint-initdb.d